# Generated by Django 4.1.7 on 2023-06-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_mother',
            new_name='phone',
        ),
    ]
